apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ld-bot
    provider: github
    repository: test-ui-react
  name: ld-bot-test-ui-react
spec:
  description: Imported application for ld-bot/test-ui-react
  httpCloneURL: https://github.com/ld-bot/test-ui-react.git
  org: ld-bot
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: test-ui-react
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/ld-bot/test-ui-react.git
